# Generated by Django 3.0.2 on 2020-06-08 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('userID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('first', models.CharField(max_length=255)),
                ('last', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('calorieIntake', models.IntegerField()),
                ('targetWeight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last logged in')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('addressTypeID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('addressTypeName', models.CharField(choices=[('Home', 'Home'), ('Student', 'Student'), ('Business', 'Business'), ('Work', 'Work'), ('Other', 'Other')], max_length=255)),
                ('addressLastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('exerciseTypeID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('exerciseTypeName', models.CharField(max_length=255)),
                ('dateCompleted', models.DateField()),
                ('achievedTarget', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('foodName', models.CharField(max_length=255)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goalID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('goalName', models.CharField(max_length=255)),
                ('goalType', models.CharField(max_length=255)),
                ('goalDescription', models.TextField()),
                ('dateCreated', models.DateField(auto_now=True)),
                ('targetDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('groupID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('groupName', models.CharField(max_length=255)),
                ('groupDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BodyWeight',
            fields=[
                ('exercisetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthTrackerApp.ExerciseType')),
                ('completedWithWeights', models.BooleanField()),
                ('howHeavyWereWeights', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('targetReps', models.IntegerField()),
                ('howManyReps', models.IntegerField()),
            ],
            bases=('healthTrackerApp.exercisetype',),
        ),
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('exercisetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthTrackerApp.ExerciseType')),
                ('distanceCompleted', models.DecimalField(decimal_places=2, max_digits=4)),
                ('targetDistance', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=('healthTrackerApp.exercisetype',),
        ),
        migrations.CreateModel(
            name='WeightLifting',
            fields=[
                ('exercisetype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='healthTrackerApp.ExerciseType')),
                ('ammountOfWeightLifted', models.DecimalField(decimal_places=1, max_digits=4)),
                ('targetWeightToLift', models.DecimalField(decimal_places=1, max_digits=4)),
                ('howManyReps', models.IntegerField()),
            ],
            bases=('healthTrackerApp.exercisetype',),
        ),
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('userGoalID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('isAchieved', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(db_column='goalID', on_delete=django.db.models.deletion.CASCADE, to='healthTrackerApp.UserGroups')),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembersInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(db_column='groupID', on_delete=django.db.models.deletion.CASCADE, to='healthTrackerApp.UserGroups')),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('mealID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('typeOfMeal', models.CharField(max_length=255)),
                ('timeRecorded', models.DateTimeField()),
                ('portionSize', models.IntegerField()),
                ('food', models.ForeignKey(db_column='foodID', on_delete=django.db.models.deletion.CASCADE, to='healthTrackerApp.Food')),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupGoals',
            fields=[
                ('groupGoalID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('isAchieved', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(db_column='goalID', on_delete=django.db.models.deletion.CASCADE, to='healthTrackerApp.UserGroups')),
                ('group', models.ForeignKey(db_column='groupID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exerciseID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('exerciseName', models.CharField(max_length=255)),
                ('timeStarted', models.TimeField()),
                ('duration', models.TimeField()),
                ('exerciseTypeID', models.ForeignKey(db_column='exerciseTypeID', on_delete=django.db.models.deletion.CASCADE, to='healthTrackerApp.ExerciseType')),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('addrLine1', models.CharField(max_length=255)),
                ('addrLine2', models.CharField(blank=True, max_length=255)),
                ('addrLine3', models.CharField(blank=True, max_length=255)),
                ('addrLine4', models.CharField(blank=True, max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=7)),
                ('addressType', models.ForeignKey(db_column='addressTypeID', on_delete=django.db.models.deletion.CASCADE, to='healthTrackerApp.AddressType')),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
